version: '3.3'
services:
  guacd:
    image: dushixiang/guacd:1.3.0
    volumes:
      - ./data:/usr/local/next-terminal/data
    restart:
          always
  next-terminal:
    image: dushixiang/next-terminal:v1.2.2
    environment:
      DB: sqlite
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    ports:
      - "8080:8088"
      - "8089:8089"
    volumes:
      - ./data:/usr/local/next-terminal/data
      - /.ssh/id_rsa:/root/.ssh/id_rsa
    restart:
      always
